import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import Accordion from "@mui/material/Accordion";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";
import Typography from "@mui/material/Typography";
import mercadopago from "mercadopago";
import type { NextPage } from "next";
import Head from "next/head";
import * as React from "react";
import { Card } from "../components/card";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [expanded, setExpanded] = React.useState<string | false>(false);

  const handleChange =
    (panel: string) => (event: React.SyntheticEvent, isExpanded: boolean) => {
      setExpanded(isExpanded ? panel : false);
    };

  const mercadoPagoPublicKey =
    process.env.NEXT_PUBLIC_MERCADO_PAGO_SAMPLE_PUBLIC_KEY;
  if (!mercadoPagoPublicKey) {
    console.warn("Error: public key not defined");
    process.exit(1);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to test api Mercado Pago</h1>
        <Accordion
          className={styles.accordion}
          expanded={expanded === "panel1"}
          onChange={handleChange("panel1")}
        >
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel1bh-content"
            id="panel1bh-header"
          >
            <Typography sx={{ width: "33%", flexShrink: 0 }}>
              Credit Card
            </Typography>
            <Typography sx={{ color: "text.secondary" }}>
              Test Credit Card as payment method
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Card />
          </AccordionDetails>
        </Accordion>
        <Accordion
          className={styles.accordion}
          expanded={expanded === "panel2"}
          onChange={handleChange("panel2")}
        >
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel2bh-content"
            id="panel2bh-header"
          >
            <Typography sx={{ width: "33%", flexShrink: 0 }}>Pix</Typography>
            <Typography sx={{ color: "text.secondary" }}>
              Test Pix as payment method
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography>
              Donec placerat, lectus sed mattis semper, neque lectus feugiat
              lectus, varius pulvinar diam eros in elit. Pellentesque convallis
              laoreet laoreet.
            </Typography>
          </AccordionDetails>
        </Accordion>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const mercadoPagoAccessToken = process.env.MERCADO_PAGO_SAMPLE_ACCESS_TOKEN;
  if (!mercadoPagoAccessToken) {
    console.log("Error: access token not defined");
    process.exit(1);
  }

  mercadopago.configurations.setAccessToken(mercadoPagoAccessToken);

  return {
    props: {},
  };
}
export default Home;
